spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    jdbc-url: jdbc:mariadb://localhost:3306/webdb
    username: jihyun
    password: 0000

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
