#spring:
#  datasource:
#    driver-class-name: org.mariadb.jdbc.Driver
#    url: jdbc:mariadb://localhost:3306/webdb
#    username: jihyun
#    password: 0000

# 데이터베이스 연결 설정
spring:
  datasource:
    jdbc-url: jdbc:mysql://localhost:3306/webdb
    username: jihyun
    password: 0000
    driver-class-name: org.mariadb.jdbc.Driver

# MyBatis 설정
mybatis:
  mapper-locations: classpath:mybatis/mapper/**/*.xml
